print("hello world")
print("1.500g of flour, 100g of yeast,300ml of water in a bowl.")
print("2.knead the dough for 10 mins.")
print("3.add 3g of salt.")
print("4.leave to rise for 2hours.")
print("5.bake at 200 degree celcius for 30 mins.")
print("she said: \"hello\"to her friend.")
print('she said:"hello"and then left.')
print("hello world!\nHello python!\nHello world!")
print("hello"+"python")